### ISSUE TITLE
ninja failure - meson 0.57.1

### ISSUE THREAD

**Issue by vincentmr** [acroucher/zofu#5]
`ninja -C build` fails when using meson 0.57.1. All meson versions work up to 0.57.0. This issue is related to the module files. Here is the log

```shell 
ninja: Entering directory `build'
[1/35] Compiling Fortran object libzofu.so.p/_tmp_vincentm_zofu_src_zofu_scan.F90.o
FAILED: libzofu.so.p/_tmp_vincentm_zofu_src_zofu_scan.F90.o 
mpifort -Ilibzofu.so.p -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -O3 -fPIC -Wno-maybe-uninitialized -Jlibzofu.so.p -o libzofu.so.p/_tmp_vincentm_zofu_src_zofu_scan.F90.o -c /tmp/vincentm/zofu/src/zofu_scan.F90
/tmp/vincentm/zofu/src/zofu_scan.F90:21:6:

   21 |   use zofu_str_utils
      |      1
Fatal Error: Cannot open module file ‘zofu_str_utils.mod’ for reading at (1): No such file or directory
compilation terminated.
[3/35] Compiling Fortran object libzofu.so.p/_tmp_vincentm_zofu_src_zofu.F90.o
FAILED: libzofu.so.p/_tmp_vincentm_zofu_src_zofu.F90.o 
mpifort -Ilibzofu.so.p -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -O3 -fPIC -Wno-maybe-uninitialized -Jlibzofu.so.p -o libzofu.so.p/_tmp_vincentm_zofu_src_zofu.F90.o -c /tmp/vincentm/zofu/src/zofu.F90
/tmp/vincentm/zofu/src/zofu.F90:23:6:

   23 |   use zofu_str_utils
      |      1
Fatal Error: Cannot open module file ‘zofu_str_utils.mod’ for reading at (1): No such file or directory
compilation terminated.
[4/35] Compiling Fortran object libzofu.so.p/_tmp_vincentm_zofu_src_zofu_mpi.F90.o
FAILED: libzofu.so.p/_tmp_vincentm_zofu_src_zofu_mpi.F90.o 
mpifort -Ilibzofu.so.p -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -O3 -fPIC -Wno-maybe-uninitialized -Jlibzofu.so.p -o libzofu.so.p/_tmp_vincentm_zofu_src_zofu_mpi.F90.o -c /tmp/vincentm/zofu/src/zofu_mpi.F90
/tmp/vincentm/zofu/src/zofu_mpi.F90:23:6:

   23 |   use zofu
      |      1
Fatal Error: Cannot open module file ‘zofu.mod’ for reading at (1): No such file or directory
compilation terminated.
[5/35] Compiling Fortran object libzofu.so.p/_tmp_vincentm_zofu_src_zofu_str_utils.F90.o
ninja: build stopped: subcommand failed.
```

**Comment by acroucher** [comment]
So ninja is failing when you try to build the Zofu library?

If so, and it worked with previous versions of Meson, it sounds like a Meson regression bug (not the first time I've encountered one of those, especially with Fortran support).

The obvious workaround is just to pin the Meson version at e.g. 0.57.0 when you install, until it is fixed. If you agree it looks like a regression I can raise an issue on the Meson repository.

**Comment by vincentmr** [comment]
I agree, that this is a Meson regression, and with the proposed fix. 

I was wondering whether Meson's interface changed again causing a problem in this block
```
  # NB this is a temporary measure until Meson gets specific
  # functionality for installing Fortran modules:
  if meson.version().version_compare('<0.55')
    mod_dir = 'zofu@sha'
  else
    mod_dir = zofu.full_path().split('/').get(-1) + '.p'
  endif
```
I'm not familiar enough with Meson to see what's wrong here. If we're in the same situation, the issue should be raised on Meson indeed.

**Comment by acroucher** [comment]
I don't think that mod_dir stuff is the problem- that only does anything when you install the library. It looks like Meson has messed something up so that it can't even build Zofu, so it's not getting to the install stage.

I wonder if it'd be possible to come up with a minimal example we could use to raise an issue with the Meson folks?

**Comment by vincentmr** [comment]
If you'd like, I can post an issue on meson's repo saying that 
```
git clone git@github.com:acroucher/zofu.git
cd zofu
FC=mpifort meson build --buildtype=release --prefix=$PREFIX --libdir=lib/ -Dmpi_wrapper_compiler=true
```
used to work just fine up to 0.57.0 and it stopped working in 0.57.1. Then see if they have something to propose right off the bat.

**Comment by acroucher** [comment]
What happens if you build it in serial, i.e. ``meson build --buildtype=release --prefix=$PREFIX --libdir=lib/`` - does that have the same problem?

**Comment by acroucher** [comment]
It's OK, I just tried this myself. I set up a Vagrant VM running Debian 10, which has Python 3.7.3, set up a Python 3 virtual environment to test in, ran ``pip install meson`` in it, which installed Meson 0.57.1. I also apt-get installed git, pkg-config, ninja-build and gfortran.

I then cloned Zofu and built, first just a serial-only version with ``meson build --buildtype=release --prefix=/home/vagrant --libdir=lib``. That built and installed ok with ``ninja -C build`` and ``ninja -C build install``.

Then I uninstalled Zofu again, installed libopenmpi-dev, and did it again (same meson build command as above). This time it detected MPI , built Zofu and I could run the unit tests in parallel.

Finally I tried doing what you were doing and used the wrapper compiler explicitly via the ``-Dmpi_wrapper_compiler`` option (NB you shouldn't need to do that unless the wrapper compiler is in some weird place, e.g. on Cray machines, and Meson can't find it). So ``FC=mpifort meson build --buildtype=release --prefix=/home/vagrant --libdir=lib -Dmpi_wrapper_compiler=true``. That built OK too.

So I am not sure what is causing the behaviour you are seeing. Unless there is something wrong with the $PREFIX environment variable you are passing to Meson?

You could also try without using the ``-Dmpi_wrapper_compiler`` option and see if that works?

**Comment by vincentmr** [comment]
My laptop is running Ubuntu 20.04. Looking more carefully, I realized that my path would point to an openmpi installation done by spack. I fixed that to use the `mpifort` program in `/usr/bin`, installed via `apt-get install libopenmpi-dev`. I reinstalled Meson 0.57.1 and tried to install simply calling `meson build --buildtype=release --prefix=/tmp/.local --libdir=lib/`. Indeed, MPI is detected automatically. I get the same error as before, but ...

If I loop between `ninja -C build` and `cd build && ninja && cd..`, the missing module error message will change 3-4 times until finally Zofu is compiled. And `meson test` shows all is fine, including parallel tests. 

The computer where it originally happened also runs Ubuntu 20.04, but it is currently down so I cannot test there. 

I think I'll stick to Meson 0.57.0 for a little while, see whether things resolve themselves. I don't need to investigate that further for now so I think we could close the issue.

**Comment by acroucher** [comment]
I have just run the Zofu CI pipeline on Github. They are using Ubuntu 20.04 for `ubuntu-latest` now as well (was 18.04 until recently).

It has the same issue you describe. I have just pushed a Zofu commit freezing the Meson version at 0.57.0 and that fixes it.

I'm not sure if this is an Ubuntu issue (since it doesn't happen on Debian) or a Meson issue (since it doesn't happen on Meson 0.57.0). Or some sort of combination.
